name: "Unit Tests"
on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Buildkite Plugin Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - run: docker-compose run --rm plugin-test
